# Generated by Django 4.2.4 on 2023-08-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_userprofile_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
