# Generated by Django 4.2.4 on 2023-08-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_contactprofile_options_alter_media_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="skill_type",
            field=models.CharField(
                choices=[
                    ("PL", "Programming Language"),
                    ("FW", "Framework"),
                    ("DB", "Database"),
                    ("OT", "Other..."),
                ],
                default="PL",
                max_length=2,
            ),
        ),
    ]
