# Generated by Django 4.2.4 on 2023-08-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_skill_skill_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="credential_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="credential_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="issue_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
