# Generated by Django 4.2.4 on 2023-08-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_remove_certificate_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="issuing_org",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
