# Generated by Django 4.2.4 on 2023-08-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_certificate_issuing_org"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_of_company",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "name_of_position",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("exit_date", models.DateField(blank=True, null=True)),
                (
                    "company_image",
                    models.ImageField(blank=True, null=True, upload_to="company"),
                ),
                ("is_current_company", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experience",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="experience",
            field=models.ManyToManyField(blank=True, to="main.experience"),
        ),
    ]
